//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace instagram_css
{
    using System;
    using System.Collections.Generic;
    
    public partial class instaTable
    {
        public int instaID { get; set; }
        public string instaUrl { get; set; }
    }
}
